### ISSUE TITLE
Wishes

### ISSUE THREAD

**Issue by saz59** [tonimelisma/fastgallery#1]
Thank you so much for a great job.
wishes:
Switch to full-screen mode.
Back buttons all the way down to the root.
Instead of a folder icon, an image from a file with a prefix (for example _file.jpg or @ file.jpg or # file.jpg) in the corresponding folder.

**Comment by tonimelisma** [comment]
Hey @saz59, thanks a lot for the feedback!

What do you mean with "switch to full-screen mode"? When you click on a picture or video, it shows up as a full-screen modal on top of the thumbnails doesn't it?

Back buttons I will implement for sure.

For the folder icons I'll need to think about it. This would require manual work from the photo gallery creator to create such folder icons... Ideally fastgallery should work on any folder structure of pictures automatically with no manual work.

Potentially in the future we might switch the built-in web gallery to a plugin system where you can use other templating systems besides the built-in one, perhaps then one could build a template that does something similar.

**Comment by saz59** [comment]
Hi Toni.
For the folder icons - 
There may be a random slide show from the corresponding folder.

**Comment by saz59** [comment]
"switch to full-screen mode"?
What I meant was: when the button is clicked, the browser goes into fullscreen mode (and maybe a slideshow starts).

**Comment by tonimelisma** [comment]
Hey saz59. The previous version of fastgallery actually showed the first picture from the corresponding folder in the thumbnail view, and had a small folder icon next to the name to indicate it's a folder. However, this made it difficult for users to understand whether a given icon is a folder or an image. After extensive testing with end users I realized it's best to just show a folder icon so it's clear that it's a folder.

There might also be folders that don't have any pictures inside them, just more subfolders. In this case it would be even more difficult to differentiate between folders and images, with some folder icons showing images and others not.

To be honest I'm doing this project in my spare time so any front-end design or coding skill contributions are greatly appreciated. If you or anyone can contribute a good design that has a folder icon with a small, optional picture that looks nice and makes it easy to differentiate between folders and images (whether the folder has an image inside or not) then I'm all open to ideas!

**Comment by tonimelisma** [comment]
@saz59 I've added the back button.
